# -*- Makefile -*-

# This Makefile defines
# 1. all the projects present in this repository
# 2. any subsets that exist here (can also be defined in any user Makefile)

# directories in arbitrary order
DIRS := libAAA frobnicator

# arbitrary subsets can be defined like
# lib_SUBSET := libAAA libBBB
