# -*- Makefile -*-

# define compilers, linkers here. The commented-out settings below are the
# defaults
#
# CC        := gcc
# CXX       := g++
# CC_LINKER := $(CC)

# Various build flags to apply to this project. Things like global warning
# settings and various paths go here. Any global pkgconfig calls can go here as
# well:
# CCXXFLAGS := `pkg-config --cflags somelib`
# LDLAGS    := `pkg-config --libs   somelib`
#
# CCXXFLAGS := -Werror -Wall
